// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color': string;
  'root': string;
  'size': string;
  'width': string;
}
export const cssExports: CssExports;
export default cssExports;
